### ISSUE TITLE
VoiceOver not working in Telegram

### ISSUE THREAD

**Issue by dw-b** [peter-iakovlev/Telegram-iOS#14]
Neither Telegram Messenger for iOS (5.1.1) nor  Telegram X (5.0.17) support Apple VoiceOver; as such both are totally inaccessible to the visually impaired (blind).

Other mainstream messengers provide this support and have done for years.

Apple make adding support for VoiceOver straightforward. https://developer.apple.com/documentation/uikit/accessibility/supporting_voiceover_in_your_app)

**Comment by nkreer** [comment]
Users who require Switch Controls are also affected by this.

**Comment by eat1k** [comment]
As of 5.5 update it's supported now.

**Comment by dw-b** [comment]
Indeed it is
