### ISSUE TITLE
FFMPEG Compile Error: invalid operand for inline asm constraint 'i'

### ISSUE THREAD

**Issue by shivanraptor** [peter-iakovlev/Telegram-iOS#22]
I'm building Telegram Fork, but failed with FFMPEG Compile Error. Build log is below:

```
building armv7...
AR	libavformat/libavformat.a
CC	libavcodec/h264_direct.o
CC	libavcodec/h264_picture.o
CC	libavcodec/h264_ps.o
CC	libavcodec/h264_refs.o
CC	libavcodec/h264_sei.o
CC	libavcodec/h264_slice.o
CC	libavcodec/h264chroma.o
CC	libavcodec/h264data.o
CC	libavcodec/h264dec.o
CC	libavcodec/h264dsp.o
CC	libavcodec/h264idct.o
CC	libavcodec/h264pred.o
CC	libavcodec/h264qpel.o
error: invalid operand for inline asm constraint 'i' at line 5747697
make: *** [libavcodec/h264_direct.o] Error 1
make: *** Waiting for unfinished jobs....
error: invalid operand for inline asm constraint 'i' at line 5438132
make: *** [libavcodec/h264idct.o] Error 1
error: invalid operand for inline asm constraint 'i' at line 5418997
make: *** [libavcodec/h264dsp.o] Error 1
error: invalid operand for inline asm constraint 'i' at line 5435979
make: *** [libavcodec/h264pred.o] Error 1
error: invalid operand for inline asm const
```

How to tackle this problem?

System Info:
- Xcode 10.1
- macOS 10.14.2

Output of `gcc --version`:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by w1217358955** [comment]
![image](https://user-images.githubusercontent.com/15319616/52895604-ecbcf380-31f7-11e9-9488-738fb50d0454.png)

System Info:

* Xcode 10.1
* macOS 10.14.2

**Comment by w1217358955** [comment]
failed with FFMPEG Compile Error Too.
`building armv7...
AR	libavformat/libavformat.a
CC	libavcodec/h264_direct.o
CC	libavcodec/h264_picture.o
CC	libavcodec/h264_ps.o
CC	libavcodec/h264_refs.o
CC	libavcodec/h264_sei.o
CC	libavcodec/h264_slice.o
CC	libavcodec/h264chroma.o
CC	libavcodec/h264data.o
CC	libavcodec/h264dec.o
CC	libavcodec/h264dsp.o
CC	libavcodec/h264idct.o
CC	libavcodec/h264pred.o
CC	libavcodec/h264qpel.o
CC	libavcodec/idctdsp.o
error: invalid operand for inline asm constraint 'i' at line 5747712
make: *** [libavcodec/h264_direct.o] Error 1
make: *** Waiting for unfinished jobs....
error: invalid operand for inline asm constraint 'i' at line 5438147
make: *** [libavcodec/h264idct.o] Error 1
error: invalid operand for inline asm constraint 'i' at line 5419012
make: *** [libavcodec/h264dsp.o] Error 1
error: invalid operand for inline asm constraint 'i' at line 5435994
make: *** [libavcodec/h264pred.o] Error 1
error: invalid operand for inline asm constraint 'i' at line 5461929
make: *** [libavcodec/h264qpel.o] Error 1`

* Xcode 10.1
* macOS 10.14.2

**Comment by w1217358955** [comment]
<asdasdasd>

**Comment by w1217358955** [comment]
System Info:
* Xcode 10.1
* macOS 10.14.2

failed with FFMPEG Compile Error Too

```
building armv7...
AR	libavformat/libavformat.a
CC	libavcodec/h264_direct.o
CC	libavcodec/h264_picture.o
CC	libavcodec/h264_ps.o
CC	libavcodec/h264_refs.o
CC	libavcodec/h264_sei.o
CC	libavcodec/h264_slice.o
CC	libavcodec/h264chroma.o
CC	libavcodec/h264data.o
CC	libavcodec/h264dec.o
CC	libavcodec/h264dsp.o
CC	libavcodec/h264idct.o
CC	libavcodec/h264pred.o
CC	libavcodec/h264qpel.o
CC	libavcodec/idctdsp.o
error: invalid operand for inline asm constraint 'i' at line 5747712
make: *** [libavcodec/h264_direct.o] Error 1
make: *** Waiting for unfinished jobs....
error: invalid operand for inline asm constraint 'i' at line 5438147
make: *** [libavcodec/h264idct.o] Error 1
error: invalid operand for inline asm constraint 'i' at line 5419012
make: *** [libavcodec/h264dsp.o] Error 1
error: invalid operand for inline asm constraint 'i' at line 5435994
make: *** [libavcodec/h264pred.o] Error 1
error: invalid operand for inline asm constraint 'i' at line 5461929
make: *** [libavcodec/h264qpel.o] Error 1
```
