### ISSUE TITLE
What is APP_CONFIG_DATA ?

### ISSUE THREAD

**Issue by shivanraptor** [peter-iakovlev/Telegram-iOS#28]
In version Telegram 5.5, I saw from `BuildConfig.m` in `Telegram-iOS` that it reads a constant called `APP_CONFIG_DATA` in line 277. It is added at commit f5880c1a3c63a77179f1c4790716da0bc7e3a6c0.

What should be the value of it? Thanks.

**Comment by Rdxer** [comment]
What is format ?

**Comment by shivanraptor** [comment]
from `BuildConfig.m`, it seems it's a meaningful HEX string. See line 277:

https://github.com/peter-iakovlev/Telegram-iOS/blob/master/Telegram-iOS/BuildConfig.m

I added the `APP_CONFIG_DATA` with empty string value to the config file, under GLOBAL_CONSTANT field. The App can be compiled but caught dead with the `assert()` at line 291.

**Comment by visoon** [comment]
Do u find the solution? @shivanraptor

**Comment by shivanraptor** [comment]
Not yet. Totally no clue on how to solve it. Compared with previous commits, it is related to API Level 23, and it should not and could not be skipped.

**Comment by shivanraptor** [comment]
**Further investigation:** If I comment out the related lines (line 277 - 332) in `BuildConfig.m` regarding the `APP_CONFIG_DATA`, the app can be loaded without problems (well, kind of), except for no new message can be received or sent. The status says "Updating..." forever. It's believed that the `APP_CONFIG_DATA` plays an important role in the latest API / App version 5.5.

![Updating forever](https://user-images.githubusercontent.com/997890/55306684-95ad6e00-5487-11e9-867c-85f481dd7c6e.png)

**Comment by SpectreMz** [comment]
Hi Shiva, have you tried to add the APP_CONFIG_DATA in the global constants?
Set up It to = 0.

**Comment by xianhe92** [comment]
I think APP_CONFIG_DATA is bytes contain your app_id and api_hash, maybe "hockeyAppId" also, so you can set these variable directly.

**Comment by shivanraptor** [comment]
How can I combine `app_id`, `api_hash` and `hockeyAppId` into a HEX string? I have already set the `APP_CONFIG_API_ID` and `APP_CONFIG_API_HASH` obtained from Telegram Core portal into `Config-Fork.xcconfig`.

**Comment by xianhe92** [comment]
you don't have to make a HEX string, just delete those codes, then add 
_app_id = xxxx;  
api_hash = @"xxxxx";
_hockeyAppid = nil;

**Comment by shivanraptor** [comment]
Can you specify which lines to comment out / delete? And is there any side effects doing so? Thanks for your help.

**Comment by xianhe92** [comment]
line 275 to 331
No side effects

**Comment by shivanraptor** [comment]
Thanks. The exact codes are:

    _apiId = 123456;
    _apiHash = @"aaaabbbbccccddddeeeeffffededeeee";
    _hockeyAppId = nil;

**Comment by SpectreMz** [comment]
Shiva, Can you Say me What version of xcode you use and what simulator? Thanks

**Comment by shivanraptor** [comment]
I'm using Xcode 10.2 (10E125). I didn't use Simulator; use my iPhone XR instead.
