### ISSUE TITLE
No Push Notification was received via Telegram Fork (v5.5)

### ISSUE THREAD

**Issue by shivanraptor** [peter-iakovlev/Telegram-iOS#29]
I noticed that no push notification was received via Telegram Fork (v5.5).

I tried to upload the associated APNS certificate at Telegram Core web-based portal, but it always said the certificate is invalid. Already tried PEM (converted via OpenSSL command line tool) and CER (download from Apple Developer Portal) format.

How to solve this problem?

**Comment by patriciy** [comment]
Hello. I solved similar issue like this:
1. Download cert from appstore
2. Import it to your mac
3. Export it from your mac to p12 format
4. run this command with your cert
openssl pkcs12 -in apns-dev-cert.p12 -out apns-dev-cert.pem -nodes -clcerts
5. Upload resulting file to telegram

**Comment by shivanraptor** [comment]
APNS Certificate upload is successful, thanks! I do think that Telegram should provide more documentation about this.

**Comment by rinkubasnal** [comment]
@shivanraptor i already tried to upload development mode .pem file on telegram platform but platform is not showing message whether uploaded file is successful or not and when i upload production mode .pem file, it shows invalid certificate. please help me in this.

**Comment by shivanraptor** [comment]
@rinkubasnal Read the comment above carefully. You have to regenerate the PEM certificate into Telegram-compatible format.

**Comment by rinkubasnal** [comment]
thanks @shivanraptor Notification is running

**Comment by saniaxxx** [comment]
> I completed all the operations but did not receive the notification

hi, did you solve the problem?
