### ISSUE TITLE
ERROR: opus not found using pkg-config

### ISSUE THREAD

**Issue by hcl24** [peter-iakovlev/Telegram-iOS#50]
building x86_64...
ERROR: opus not found using pkg-config
If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

I can't resolve it.

**Comment by shivanraptor** [comment]
See #21

**Comment by hcl24** [comment]
> 见[＃21](https://github.com/peter-iakovlev/Telegram-iOS/issues/21)

**Comment by hcl24** [comment]
I tried it and still reported the same error.

**Comment by hcl24** [comment]
Finally, I solved this problem, and this error misled me.

**Comment by 2008muyu** [comment]
> Finally, I solved this problem, and this error misled me.

how solve it?

**Comment by alifaaz** [comment]
how u solve it ????
