### ISSUE TITLE
Where is the version of the app displayed?

### ISSUE THREAD

**Issue by NightMachinary** [peter-iakovlev/Telegram-iOS#61]
I like to see which version of this app I have installed on my device, but I can’t find this info in the app?

**Comment by nisarul** [comment]
From home screen of Telegram, keep tapping on settings icon 10 times continuously to see a debug menu. At the bottom of menu, you can see current version.

**Comment by ethylmorphine** [comment]
Just go to Settings -> Privacy -> Active sessions. Don’t bother with debug menu.

**Comment by BrandonNolet** [comment]
Yeah I think the app version should be displayed more clearly than any of these solutions.

**Comment by BNolet** [comment]
Yeah I think the app version should be displayed more clearly than any of these solutions.

**Comment by KazankovMarch** [comment]
It would be helpful if we could copy the app version. Currently I can't select it's text value on my IOS telegram client.
