### ISSUE TITLE
release-5.8 WatchCommonWatch/WatchCommonWatch.h not found

### ISSUE THREAD

**Issue by shivanraptor** [peter-iakovlev/Telegram-iOS#76]
In the `release-5.8`, I'm unable to compile the source, as Xcode claims `WatchCommonWatch/WatchCommonWatch.h` cannot be found when I'm compiling the `Telegram-iOS-Fork`'s Watch Extension submodule, though the 2 targets in the newly introduced `WatchCommon` project can be successfully built.

Did I missing something important? I have already changed the entitlements, bundle IDs, and Developer identity as usual.

p.s. I just checked that the structure of `release-5.8` is quite different than the previous ones.  Why?

p.s. I think this issue list should make good use of the labels (sadly the repo owner didn't reply anything)

![Screenshot 2019-06-24 at 6 39 02 PM](https://user-images.githubusercontent.com/997890/60012770-65a0f000-96af-11e9-8af5-ca829ef1c615.png)

**Comment by xianhe92** [comment]
The selected configuration in sub projects are wrong,  maybe you should chose the right one by yourself

**Comment by shivanraptor** [comment]
> The selected configuration in sub projects are wrong, maybe you should chose a right one by yourself

Can you be more specific? I double checked, they are almost identical as their release-5.7 counterparts.

**Comment by jmluang** [comment]
Same problem, is there any one know how to fix this problem ?

**Comment by xianhe92** [comment]
> > The selected configuration in sub projects are wrong, maybe you should chose a right one by yourself
> 
> Can you be more specific? I double checked, they are almost identical as their release-5.7 counterparts.

for example, you can chose the "DebugFork" for all projects in the workspace, some sub project don't have this configuration, so, just create a new configuration named like that. only if all projects have same build configuration, then those frameworks can be found in right path

**Comment by jmluang** [comment]
> Same problem, is there any one know how to fix this problem ?

i'm using the AppStoreLLC scheme and work well.

**Comment by shivanraptor** [comment]
By creating a configuration named "DebugFork" in all projects (by duplicating "DebugAppStoreLLC"), the workspace can be built without errors. Thanks @xianhe92 !
